### ISSUE TITLE
Parse Function

### ISSUE THREAD

**Issue by mezzi10** [mezzi10/cs161#1]
You need to put some tests that show your function is doing the right thing: look for keywords : java, php, skills...etc and show that it find it in the page. Not just get the content of the page, that is only the first step.

**Comment by dado318** [comment]
Oh okay that makes sense... which URL will I be using then? I have never
done anything in php so I was just looking at the link that you sent me a
couple of weeks ago.

**Comment by dado318** [comment]
I mean from which webpage should I be looking from?

**Comment by dado318** [comment]
Or just any webpage?

**Comment by mezzi10** [comment]
You can test any url that has those keywords: java, php...etc, try any job description online
After you get the content of the web page, you need to parse it, loop though it and try to find those keywords. You can set a counter every time it finds one, it increments the counter and the final value of the counter will be the percentage we will be using to find the right candidate.

**Comment by dado318** [comment]
Got it, I will work on it tonight and update it on GitHub, thanks dude!

Btw, how is CS 147? Would you recommend the professor (Di Troia, right?!)
you're taking?
